### ISSUE TITLE
AdnRme.dll

### ISSUE THREAD

**Issue by ibhindal** [jeremytammik/AdnRme#1]
i am using revit 2021 so it should be compatible with my file but if you try and run it , it says failed to initialise the add-in "AdnRme" because the assembly "Y:\a\src....\AdnRme.dll" does not exist. this occurs on revit opening and happens every time its open unless you tell it not to show again

**Comment by jeremytammik** [comment]
This is an error in your add-in manifest. Please work through a [getting started with the Revit API tutorial](https://thebuildingcoder.typepad.com/blog/about-the-author.html#2) to understand how to correctly set up your add-in manifest. It is very easy. Then the error will go away.
